CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  surname VARCHAR(50),
  email VARCHAR(50),
  password VARCHAR(20)
);

INSERT INTO users (name, surname, email, password) VALUES
  ('John', 'Smith', 'jsmith@example.com', 'password123'),
  ('Jane', 'Doe', 'jdoe@example.com', 'password456'),
  ('Bob', 'Johnson', 'bjohnson@example.com', 'password789'),
  ('Mary', 'Williams', 'mwilliams@example.com', 'password321'),
  ('Michael', 'Brown', 'mbrown@example.com', 'password654'),
  ('Sarah', 'Davis', 'sdavis@example.com', 'password987'),
  ('David', 'Miller', 'dmiller@example.com', 'password123'),
  ('Susan', 'Wilson', 'swilson@example.com', 'password456'),
  ('Robert', 'Moore', 'rmoore@example.com', 'password789'),
  ('Jessica', 'Taylor', 'jtaylor@example.com', 'password321'),
  ('Lisa', 'Anderson', 'landerson@example.com', 'password654'),
  ('Paul', 'Thomas', 'pthomas@example.com', 'password987'),
  ('Mark', 'Jackson', 'mjackson@example.com', 'password123'),
  ('Linda', 'White', 'lwhite@example.com', 'password456'),
  ('James', 'Harris', 'jharris@example.com', 'password789'),
  ('Patricia', 'Martin', 'pmartin@example.com', 'password321'),
  ('John', 'Thompson', 'jthompson@example.com', 'password654'),
  ('Jennifer', 'Garcia', 'jgarcia@example.com', 'password987'),
  ('Matthew', 'Martinez', 'mmartinez@example.com', 'password123'),
  ('Ashley', 'Robinson', 'arobinson@example.com', 'password456'),
  ('Christopher', 'Clark', 'cclark@example.com', 'password789'),
  ('Michelle', 'Rodriguez', 'mrodriguez@example.com', 'password321'),
  ('Steven', 'Mitchell', 'smitchell@example.com', 'password654'),
  ('Margaret', 'Lee', 'mlee@example.com', 'password987'),
  ('Donald', 'Phillips', 'dphillips@example.com', 'password123'),
  ('Dorothy', 'Young', 'dyoung@example.com', 'password456'),
  ('Anthony', 'Allen', 'aallen@example.com', 'password789'),
  ('Helen', 'Sanchez', 'hsanchez@example.com', 'password321'),
  ('Jennifer', 'Lee', 'jlee@example.com', 'password987'),
  ('Joshua', 'Harris', 'jharris@example.com', 'password654');